<div><?php echo $flash['success'][0] ?></div>

<form action="/users" method="get">
    <input type="search" required name="term" value="<?php echo htmlspecialchars($term) ?>" />
    <input type="submit" value="Search">
</form>
<a href="/users">Clear filter</a>

<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td style="width: 200px;"><?php echo $user['id']; ?></td>
            <td style="width: 200px;"><?php echo $user['nickname']; ?></td>
            <td><a href="mailto:<?= $user['email'] ?>"><?= $user['email']; ?></a></td>
        </tr>
    <?php endforeach ?>
</table>

<a href="/users/new">Add new user</a>
