<form action="/users" method="POST">
    <div>
        <label>
            Nickname
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>" />
        </label>
    </div>
    <div>
        <label>
            E-mail
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" />
        </label>
    </div>
    <?php if (count($errors)): ?>
        <div>
            <?php foreach ($errors as $key => $value): ?>
                <div>
                    <?php echo "{$key}: {$value}" ?>
                </div>
            <?php endforeach ?>
        </div>
    <?php endif ?>
    <input type="submit" value="Send" />
</form>